listeners:
  - listenerAddress: "127.0.0.1:8000"
    protocol: "tcp"
    backendAddresses: 
      - "127.0.0.1:8080"
    timeoutConnect: 10
    timeoutRead: 30
    timeoutWrite: 60
    healthCheckInterval: 5
debug: true