listeners:
  - listenerAddress: "127.0.0.1:8080"
    backendAddresses: 
    - "google.com:80"
    - "youtube.com:80"
  - listenerAddress: "127.0.0.1:7070"
    backendAddresses: 
    - "google.com:80"
    - "youtube.com:80"
debug: true